site_name: SaraII - Indicadores Rurales
theme:
  name: material
  language: es

nav:
  - Conexión: conect.md
  - Funciones: funciones.md
  - Inicio: index.md
  - Información Consolidada: infCons.md
  - Información Departamental: infDep.md
  - Información Municipal: infMun.md
  - Información Nacional: infNac.md
  - Información de Proyectos: infProy.md
  - Revisión de Sesión: revSesion.md
  - Panel Principal: principal.md
  - Base de Datos (MySQL): tecnico/bd.md
  - Requerimientos: tecnico/req.md
  - Roles: tecnico/roles.md

