site_name: SaraII - Indicadores Rurales
theme:
  name: material
  language: es
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js
nav:
  - Inicio: index.md
  - Revisión de Sesión: revSesion.md
  - Panel Principal: principal.md
  - Coordinador:
    - Ind Consolidada: coordinador/infCons.md
    - Ind Departamental: infDep.md
    - Ind Municipal: infMun.md
    - Ind Nacional: infNac.md
  - Admin:
    - Inf. Actividades: admin/infConsultas.md
    - Inf. Partic-Comp: admin/infPartComp.md
    - Inf. Partic-Ind: admin/infPartInd.md
    - Inf. Proyectos: admin/infProy.md
    - Inf. Ubicaciones: admin/infListUbic.md
    - Inf. Resumen: admin/infResReg.md
  - Backend:
    - Conexión: conect.md
    - Funciones: funciones.md
  - Tecnico:
    - Base de Datos: tecnico/bd.md
    - Bd Estructura: tecnico/bdEst.md
    - Requerimientos: tecnico/req.md
    - Roles: tecnico/roles.md

