site_name: SaraII - Indicadores Rurales
theme:
  name: material
  language: es
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Inicio: index.md
  - Revisión de Sesión: revSesion.md
  - Panel Principal: principal.md
  - Coordinador:
    - Ind de intervencion consolidado: coordinador/indInterConsMVC.md
    - Ind Intervención detallado: coordinador/indInterDetGraf.md
  - Administrador:
    - Inf. Mensual Resum. de Actividades (G): admin/infAgrGrafActivRes.md
    - Inf. Mensual Det. de Actividades (T): admin/infAgrTabActivMVC.md
    - Inf. Partic: admin/infPartic.md
    - Inf. Ubicaciones: admin/infGrafUbic.md
    - Inf. Graf. de Uso: admin/infGrafUso.md
    - Inf. Proyectos: admin/infTabProy.md
  - Back:
    - Conexión: back/conexion.md
    - Estilos: back/estilos.md
    - Funciones: back/funciones.md
  - Definición:
    - Base de Datos: def/bd.md
    - Bd Estructura: def/bdEst.md
    - Requerimientos: def/req.md
    - Roles: def/roles.md

