site_name: SaraII - Indicadores Rurales
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Revisión de Sesión: revSesion.md
  - Panel Principal: principal.md
  - Coordinador:
    - Ind Consolidada: coordinador/infCons.md
    - Ind Departamental: infDep.md
    - Ind Municipal: infMun.md
    - Ind Nacional: infNac.md
  - Admin:
    - Inf. de Consultas: admin/infConsultas.md
    - Inf. de Participación - Comparativo: admin/infPartComp.md
    - Inf. de Participación - Individual: admin/infPartInd.md
    - Inf. de Proyectos: admin/infProy.md
    - Inf. del Litsado de Ubicaciones: admin/infListUbic.md
    - Inf. del Resumen de Registros: admin/infResReg.md
  - Backend:
    - Conexión: conect.md
    - Funciones: funciones.md
  - Tecnico:
    - Base de Datos (MySQL): tecnico/bd.md
    - Requerimientos: tecnico/req.md
    - Roles: tecnico/roles.md

