site_name: SaraII - Indicadores Rurales
theme:
  name: material
  language: es
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid 
nav:
  - Inicio: index.md
  - Revisión de Sesión: revSesion.md
  - Panel Principal: principal.md
  - Coordinador:
    - Ind Consolidada: coordinador/indActiv.md
    - Ind Intrvención: coordinador/indInter.md
  - Admin:
    - Inf. Actividades: admin/infConsActiv.md
    - Inf. Partic-Comp: admin/infPartComp.md
    - Inf. Partic-Ind: admin/infPartInd.md
    - Inf. Proyectos: admin/infProy.md
    - Inf. Ubicaciones: admin/infListUbic.md
    - Inf. Resumen: admin/infResReg.md
  - Back:
    - Conexión: back/conexion.md
    - Estilos: back/estilos.md
    - Funciones: back/funciones.md
  - Definición:
    - Base de Datos: def/bd.md
    - Bd Estructura: def/bdEst.md
    - Requerimientos: def/req.md
    - Roles: def/roles.md

